
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEnonassocUMINUSDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS expression\n| expression MINUS expression\n| expression TIMES expression\n| expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : MINUS expression %prec UMINUS'
    
_lr_action_items = {'LPAREN':([0,2,3,5,6,7,8,],[3,3,3,3,3,3,3,]),'NUMBER':([0,2,3,5,6,7,8,],[4,4,4,4,4,4,4,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[2,6,2,2,-6,2,2,2,2,-7,6,-1,-2,-3,-4,-5,]),'$end':([1,4,9,11,12,13,14,15,],[0,-6,-7,-1,-2,-3,-4,-5,]),'PLUS':([1,4,9,10,11,12,13,14,15,],[5,-6,-7,5,-1,-2,-3,-4,-5,]),'TIMES':([1,4,9,10,11,12,13,14,15,],[7,-6,-7,7,7,7,-3,-4,-5,]),'DIVIDE':([1,4,9,10,11,12,13,14,15,],[8,-6,-7,8,8,8,-3,-4,-5,]),'RPAREN':([4,9,10,11,12,13,14,15,],[-6,-7,15,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,5,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','tpc6.py',43),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','tpc6.py',44),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','tpc6.py',45),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','tpc6.py',46),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','tpc6.py',59),
  ('expression -> NUMBER','expression',1,'p_expression_number','tpc6.py',63),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','tpc6.py',67),
]
